# Generated by Django 4.2 on 2025-05-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_roadsegment_trafficspeed_delete_roadsegmenttraffic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadsegment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
